name: "Send to Allure Docker Service"
description: "Greet someone"
author: "unickq"

inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - run: echo Hello ${{ inputs.who-to-greet }}.
      shell: bash
    - run: ${{ github.action_path }}/send.sh
      shell: bash
