name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  allure-docker-send-example:
    runs-on: ubuntu-latest

    name: Send to Allure Docker Service

    env:
      ALLURE_SERVER_URL: ${{ secrets.ALLURE_SERVER_URL }}
      ALLURE_SERVER_USER: ${{ secrets.ALLURE_SERVER_USER }}
      ALLURE_SERVER_PASSWORD: ${{ secrets.ALLURE_SERVER_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - uses: unickq/send-to-allure-docker-service-action@main
        with:
          allure_results: allure-results-example
          project_id: actions
          auth: true
          generate: true